version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules: