version: '3.8'

services:
  vue-app:
    build:
      context: .
    container_name: vue_app
    env_file:
      - .env
    ports:
      - "3000:3000"

  ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        command:
          - "start"
          - "--all"
          - "--config"
          - "/etc/ngrok.yml"
        volumes:
          - ./ngrok.yml:/etc/ngrok.yml

volumes:
  node_modules:
